DROP TABLE order_details CASCADE CONSTRAINTS;
DROP TABLE orders CASCADE CONSTRAINTS;
DROP TABLE products CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(120) NOT NULL,
    password VARCHAR2(20) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    role VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_user_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT chk_user_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(120) NOT NULL,
    description VARCHAR2(300),
    price NUMBER(10, 2) NOT NULL,
    stock NUMBER(10) NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT chk_products_price CHECK (price >= 0),
    CONSTRAINT chk_products_stock CHECK (stock >= 0),
    CONSTRAINT chk_products_active CHECK (active IN (0, 1))
);

CREATE TABLE orders(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    order_date DATE NOT NULL,
    total_amount NUMBER(10, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CONSTRAINT fk_orders_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_order_status CHECK (status IN ('PENDING', 'COMPLETED', 'REJECTED'))
);

CREATE TABLE order_details(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    qty NUMBER NOT NULL,
    unit_price NUMBER(10, 2) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_order_details_orders FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_details_products FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT chk_order_details_qty CHECK (qty > 0),
    CONSTRAINT chk_order_details_unit_price CHECK (unit_price >= 0)
);

INSERT INTO users (name, email, password, role) VALUES ('Macarena Munoz', 'maca@storeapi.com', 'maca123', 'ADMIN');
INSERT INTO users (name, email, password, role) VALUES ('Juan Perez', 'juan@storeapi.com', 'juan123', 'USER');
INSERT INTO users (name, email, password, role) VALUES ('Pedro Martinez', 'pedro@storeapi.com', 'pedro123', 'USER');

INSERT INTO products (name, description, price, stock, active) VALUES ('Sillón', 'Sillón verde 3 cuerpos', 250990, 39, 1);
INSERT INTO products (name, description, price, stock, active) VALUES ('Teclado', 'Teclado wireless', 39990, 10, 1);
INSERT INTO products (name, description, price, stock, active) VALUES ('Monitor 27"', 'Monitor 27" HD', 390000, 17, 1);
INSERT INTO products (name, description, price, stock, active) VALUES ('Notebook Gamer', 'Notebook Gamer SSD 1TB, 16GB RAM', 890000, 12, 1);
INSERT INTO products (name, description, price, stock, active) VALUES ('TV', 'TV 65" LED', 1299900, 12, 1);

COMMIT;